/**
 * 
 */
package ch.ethz.e4mooc.shared;

import java.io.Serializable;

/**
 * DTO to send the compiler output back to client.
 * Also contains a time stamp so that the client has information
 * about when this compilation took place and if it was successful.
 * 
 * @author hce
 *
 */
public class CompilationResultDTO implements Serializable {

	/** Generated id */
	private static final long serialVersionUID = -4566647872553710759L;
	/** the output generated by the compiler */
	private String compilerOutput;
	/** the time stamp when the compilation was done */
	private String timeStamp;
	/** was the compilation successful */
	private boolean compilationSuccessful;
	
	/**
	 * Empty constructor required for serialization (don't use otherwise).
	 */
	public CompilationResultDTO() {	
	}
	
	/**
	 * Constructor
	 * @param compilerOutput the output generated by the compiler
	 * @param timeStamp the time stamp when the compilation was done 
	 * @param compilationSuccessful was the compilation successful
	 */
	public CompilationResultDTO(String compilerOutput, String timeStamp, boolean compilationSuccessful) {
		this.compilerOutput = compilerOutput;
		this.timeStamp = timeStamp;
		this.compilationSuccessful = compilationSuccessful;
	}
	
	public String getCompilerOutput() {
		return this.compilerOutput;
	}
	
	public String getTimeStamp() {
		return this.timeStamp;
	}
	
	public boolean wasCompilationSuccessful() {
		return compilationSuccessful;
	}

}
